# Generated by Django 4.1.5 on 2023-01-18 02:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mediciones", "0002_alter_medicion_fecha_hora"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicion",
            name="fecha_hora",
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
